### ISSUE TITLE
File google-services.json.enc

### ISSUE THREAD

**Issue by BrayanMC** [ashdavies/eternity#9]
Error:Execution failed for task ':mobile:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/Home/Documents/Utils/Android/Java/eternity/mobile/src/debug/google-services.json
  /Users/Home/Documents/Utils/Android/Java/eternity/mobile/google-services.json

**Comment by ashdavies** [comment]
The file `google-services.json.enc` is included so that Travis can build the project, but it would be unwise to include the unencrypted version in a public repository as it contains secrets relating to the project on Firebase.

If you would like to build the project yourself, I would advise creating a new project in Firebase and follow the guides to add the configuration file to the project.

https://firebase.google.com/docs/android/setup
